---
title: Households by AMI Forecast
format:
  html:
   code-fold: true
   code-summary: "Show the code"
   code-tools: true
   toc: true
   output: false
---

# Purpose
This script is to generate a forecast of households by AMI based on the most recent three year average at the state level.

```{r}
#| label: setup

library(tidyverse)
library(flexiblas)
library(sdotools)
library(sdodemog)
library(googledrive)
library(DBI)
library(RPostgres)

# Enable parallel processing with FlexiBLAS
flexiblas_load_backend("OPENBLAS-OPENMP")
flexiblas_set_num_threads(parallel::detectCores() - 1)

```

# Pull Data from Postgres
```{r}
#| label: pull_data

con <- sdodemog::connect_to_sdo_db()

connections::connection_view(con)

hh_by_ten_ami_state <- pull_db_table(
  schema = "econ",
  table = "hh_by_ten_ami_state"
)
hh_projections <- pull_db_table(
  schema = "estimates",
  table = "household_projections"
)

```

# Process Data

Begin by calculating by year the percentage of all households by tenure, and percentage of households by AMI group within each tenure group.

```{r}
#| label: process_data

hh_ami_pct <- hh_by_ten_ami_state |>
  select(year, tenure, ami_group, hh_ami_ten = hh) |>
  mutate(hh_tot = sum(hh_ami_ten), .by = c(year)) |>
  mutate(
    hh_ten = sum(hh_ami_ten),
    .by = c(year, tenure)
  ) |>
  mutate(
    pct_hh_ten = hh_ten / hh_tot,
    pct_hh_ami_ten = hh_ami_ten / hh_ten
  )

hh_ami_pct_fcst <- hh_ami_pct |>
  filter(year >= max(year) - 2) |>
  summarize(
    hh_ami_ten_avg = mean(hh_ami_ten),
    hh_tot_avg = mean(hh_tot),
    hh_ten_avg = mean(hh_ten),
    .by = c(tenure, ami_group)
  ) |>
  mutate(
    pct_hh_ten = hh_ten_avg / hh_tot_avg,
    pct_hh_ami_ten = hh_ami_ten_avg / hh_ten_avg
  )

hh_ami_allocation_tbl <- bind_rows(
  hh_ami_pct |>
    select(year, tenure, ami_group, pct_hh_ten, pct_hh_ami_ten),
  expand_grid(
    year = c((max(hh_ami_pct$year) + 1):max(hh_projections$year)),
    hh_ami_pct_fcst |> select(tenure, ami_group, pct_hh_ten, pct_hh_ami_ten)
  )
)

hh_ami_forecast <- hh_projections |> 
    filter(
        area_code == 0,
        household_type_id == 0,
        age_group_id == 0
    ) |> 
        left_join(
        hh_ami_allocation_tbl, by = "year"
    ) |> 
    mutate(
        hh_allocated = total_households * pct_hh_ten * pct_hh_ami_ten
        )

```

```{r}
#| label: write_data


sdodemog::sdo_db_write_table(
    con,
    schema = "econ",
    table = "ami_state_forecast",
    df = hh_ami_forecast,
    vintage = 2024
)
```